### ISSUE TITLE
Stringy functions with arguments

### ISSUE THREAD

**Issue by OleVik** [Vivalldi/grav-plugin-filter-strings#3]
The README notes:

> Note: Currently only Stringy functions that modify a string without arguments work. Other modifiers have not been tested.

Is there any ongoing work on enabling these? For example, `regexReplace()` would be very handy in manipulating Markdown-output.

**Comment by Vivalldi** [comment]
@OleVik yes. I've been preparing for graduation recently and have put this on my list of things to look into later on.

**Comment by Vivalldi** [comment]
@OleVik added support in commit 3429792be90e3412d5030f6b84dc459711d71eea
