### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ghost** [Vivalldi/grav-plugin-filter-strings#4]
No biggie, but should probably be fixed. Old links are being used here. Needs to be `filter-strings` rather than `filterStrings`. Absolutely incredible plugin though. You guys are brilliant.

![screen shot 2016-05-03 at 4 06 44 pm](https://cloud.githubusercontent.com/assets/5648875/14998356/1c694e76-1149-11e6-8c6d-0e5873fc53a3.png)

**Comment by Vivalldi** [comment]
See #2 
I see if I can release 1.0.1 to fix that

**Comment by flaviocopes** [comment]
Looks fixed!
